### ISSUE TITLE
Issues related to first task

### ISSUE THREAD

**Issue by thevaibhavmaurya** [Gari-Dev-DAO/Octernship_design_assignment#5]
Need to confirm this is the official website (https://chingari.io/) and that the website content should be the same and have to focus on the designing part.

**Comment by Gari-Dev-DAO** [comment]
Yes This is the official site https://chingari.io/ & https://nft.chingari.io the content should be a combination of both, this task is to get more understanding on your UI & UX too, & see your skills in creating product flow.
It's a open ended task to create a chingari lite web app screens created & proposed by the open source community. 
We would suggest you to go through chingari mobile app to know more about chingari's offering & user base.

**Comment by thevaibhavmaurya** [comment]
I am a Web Developer and I am not a UI UX Designer. Therefore can I make this using React Js.

**Comment by Gari-Dev-DAO** [comment]
We are looking for Design intern, Web development is good but the candidate should have the skill set to create basic UI UX & prototypes. Not expecting advanced Visual designs but this much is must. & just figma of screens would be sufficient for the task no need for creating react components.

**Comment by thevaibhavmaurya** [comment]
Accidentally, I selected [Os Contributor Assignment For Gari Repo Mantainance](https://github.com/Gari-Dev-DAO/-Octernship_OS_Contributor_assignment). 
I want to participate in this and I completed 75%. Can I make pr of assignment in that one? 

Please resolve my problem

**Comment by Gari-Dev-DAO** [comment]
Raise another Pr for the design task with your submission & make a commit to the submission you made in OS contributor mentioning the same issue as a note on top of readme or just discard that

**Comment by thevaibhavmaurya** [comment]
I willing to tell you that I made the pr in Os Contributor Assignment For Gari Repo Mantainance. 

So please 🥺 review my assignment.
